### ISSUE TITLE
Tensorflow 2

### ISSUE THREAD

**Issue by Aishaj** [TeaPoly/SpectrumAugmenter#1]
Hello, 
The current code doesn't work on tf2. Is there any chance of updating it?
Thanks

**Comment by TeaPoly** [comment]
> Hello,
> The current code doesn't work on tf2. Is there any chance of updating it?
> Thanks

Fix by https://github.com/TeaPoly/SpectrumAugmenter/commit/a923d5b491ba1b15c88466a6730ee862c6d67307
